### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by KevinEady**
I noticed that this repository does not have a license file. From [GitHub's licensing page](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license):

> However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

This PR adds a license file for the [Unlicense](https://unlicense.org/) license type. I did not want to assume a license, but I wanted to create a PR to make this as easy as possible for you. Please let me know.

Thanks, Kevin

### CODE REVIEW

**Comment by depp** [comment]
Have you gotten permission from the author of CoreSDL? This can’t be merged, otherwise.

**Comment by KevinEady** [comment]
Nope. I thought you were the original owner of this code by correctly figuring out the signatures for the P/Invoke etc, but I guess I am incorrect...?

I am interested in incorporating this library in another open-source project, and not sure the correct procedures to ensure correct copyrights taken.

**Comment by depp** [comment]
The authors of the code are listed in the commits, you would have to contact both of them for permission to relicense the code.

**Comment by KevinEady** [comment]
Looks like the authors are @jesta88 and @tuxuser , and I have no way to contact them other than this comment's @-mention. If they review the PR and approve the changes, would that suffice as permission? If so, I can keep this PR open for a few days.

**Comment by KevinEady** [comment]
Since there has been no activity, I suppose I will close this. Thanks all.

**Comment by tuxuser** [comment]
Oops sorry, I totally missed this one.
It's fine for me, but I just contributed little things.. Actual creator is of course @jesta88

**Pull request closed without merging**
